### ISSUE TITLE
Inverser Que va t'il devenir ? & Comment éviter de le produire ?

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/quefairedemesdechets#1]
J'inverserais les deux blocs pour que ce soit plus logique dans le sens de la lecture :

-> Quoi en faire
-> Où le jeter 
-> Que va t-il devenir 
-> Cmt éviter de le produire

**Comment by florianpanchout** [comment]
Je teste une nouvelle mise en page pour ces parties (CE N'EST PAS RESPONSIVE ENCORE). Vous en pensez quoi ?

![Screenshot 2021-05-06 at 14 57 15](https://user-images.githubusercontent.com/8115933/117301922-66923380-ae7b-11eb-9b1d-d215ba3500e5.png)

**Comment by martinregner** [comment]
Top !! 🤩 
Je trouve ça plus lisible que les blocs successifs (pas grave si pas responsive pour le moment)

**Comment by florianpanchout** [comment]
C'est responsive :)

**Comment by florianpanchout** [comment]
Est ce qu'on ouvre la map par défaut ? Ou alors on laisse tout fermé ?

**Comment by Clem-mrtn** [comment]
Trop cool ! C'est mieux comme ça, plus digeste ! 

Moi je laisserai la map ouverte par défaut, ça fait son petit effet 
Sinon on aurait que les en tête ? (Ou l'apporter ? Que va t-il devenir ? etc.)

**Comment by martinregner** [comment]
En laissant fermé on voit p-e mieux les 2 ou 3 boutons possible et le en savoir + ?

Il faut surtout vérifier que l'on a des cartes à afficher pour la majorité des articles, c'est pas certain du tout (mais ça on regardera au go définitif ;)

**Comment by florianpanchout** [comment]
99.7% des produits ont "Que va t'il devenir ?"
55% des produits ont "Comment les éviter ?"
No idea pour les points de dépôt 

390 produits
389 "Que va t'il devenir ?"
215 "Comment les éviter ?"

**Comment by florianpanchout** [comment]
J'ai changé pour que la carte soit ouverte par défaut (et s'il n'y a pas de point d'apport, c'est "Que va t'il devenir" qui est ouvert par défaut)

**Comment by florianpanchout** [comment]
À noter qu'au moins 40% des produits ont la map (pour les déchèteries). Ça devrait fortement augmenter avec les autres points d'apports

**Comment by martinregner** [comment]
C'est top !!

On croise les doigts pour avoir bientôt les autres ... 🤞

**Comment by florianpanchout** [comment]
Je réouvre cette issue parce que j'ai à nouveau changé la présentation de la page déchet : 

J'ai vraiment l'impression que le système d'onglet fait passer à côté de "Que va t'il devenir ?" et "Comment éviter de le produire ?". Vous en pensez quoi ?

(J'ai laissé les 3 boutons sur mobile par contre, ou c'est plus embêtant d'avoir trop de contenu)
