### ISSUE TITLE
Nous contacter > Votre sujet

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#10]
Modifier la liste des choix possible pour les sujets de contacts : 
- Je souhaite obtenir de l'aide pour intégrer le simulateur
- Je souhaite en savoir plus sur Datagir
- Je souhaite signaler une erreur pour un déchet
- Je souhaite signaler un déchet manquant
- Autre

**Comment by florianpanchout** [comment]
Done
