### ISSUE TITLE
Mise à jour texte de partage

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#11]
### Partage du simulateur

Titre : Que faire de mes déchets
Contenu : Vous voulez vérifier si vous respectez bien les consignes de tri pour vos emballages, pots de peinture ou médicaments ? Vous vous demandez où apporter vos appareils électriques, votre ordinateur ou vos vêtements ? Toutes les réponses sont ici

### Partage du résultat

(si facile d'ajouter le _Nom du déchet_, sinon on fera sans)

Titre : Que faire de mes déchets - _Nom du déchet_
Contenu : Je viens de découvrir comment jeter _Nom du déchet_, ce qu'il va devenir mais aussi comment l'éviter. Je pense que cela pourra aussi t'intéresser, n'hésite pas à voir tous les détails sur ce site de l'ADEME.

**Comment by florianpanchout** [comment]
On a un problème de ton non ? Dans un cas on parle en tant que Que Faire de mes Déchets, et dans l'autre on parle à la place de l'utilisateur

**Comment by florianpanchout** [comment]
Est ce que ce ne serait pas plus logique de faire cette séparation de ton selon le média ? "Tu" pour Whatsapp et Mail, "Vous" pour Facebook, Twitter et Linkedin

**Comment by florianpanchout** [comment]
Compliqué d'intégrer le nom du déchet dans une phrase :

> Je viens de découvrir comment jeter Seringue sans aiguille (contaminée), ce qu'il va devenir, mais...

J'ai essayé de faire au mieux en prenant en compte la spécificité de chaque réseau. Les textes sont visible ici : https://github.com/datagir/quefairedemesdechets/blob/master/src/components/wrappers/ShareWrapper.js

**Comment by Clem-mrtn** [comment]
MAJ du ticket avec les textes rédigés dans le nextcloud : https://cloud.datagir.com/index.php/apps/files/?dir=/Datagir/Dev&fileid=5673

**Comment by florianpanchout** [comment]
C'est fait !

**Comment by Clem-mrtn** [comment]
Possible de rajouter des emojis comme sur le doc ? (ils étaient dans les titres) => Pour aérer un peu le texte et renforcer le côté communication sur les RS 

+ sur Linkedin je n'ai rien qui s'affiche, je dois cliquer sur **Partager dans un post** : c'est normal ? Pas possible de paramétrer d'avance des textes ? Je me rappelle plus 
![image](https://user-images.githubusercontent.com/76995768/133395859-58e32adf-0859-4cc5-b632-0bf79b07a9de.png)

**Comment by florianpanchout** [comment]
Yes, il n'est pas possible de faire mieux sur Linkedin finalement :/

C'est bon pour les emojis ! ♻🌍

**Comment by martinregner** [comment]
Image à mettre à jour.

**Comment by florianpanchout** [comment]
Laquelle ? La meta est ok non ? https://quefairedemesdechets.netlify.app/metaimage.png
