### ISSUE TITLE
Charte site

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#12]
Au vu de la visibilité du site et les attentes qu'il suscite côté ministère, la com souhaite être un peu + carré côté charte / design system / accessibilité.

Cela nous permettra de garder une landing page en propre.

A ce stade, je propose de simplement modifier le header en ajoutant les logos genre :

![image](https://user-images.githubusercontent.com/46482115/127159078-3fdb244f-622c-41e7-afbb-7ff3b8559ff2.png)

**Comment by florianpanchout** [comment]
Donc mettre le thème blanc par défaut ?

**Comment by florianpanchout** [comment]
(on peut essayer de reprendre le bleu et le rouge Ademe aussi)

**Comment by martinregner** [comment]
> Donc mettre le thème blanc par défaut et afficher les logos en haut ?

Surtout les logos en haut.
Pour le thème, c'est sans doute plus harmonieux en blanc avec les logos oui, sans obligation. Ca peut aussi être juste un bandeau blanc pour les logos.

> (on peut essayer de reprendre le bleu et le rouge Ademe aussi)

Ce n'est pas choquant comme ça, il ne s'agit pas forcément d'avoir les couleurs Mariane partout...

**Comment by florianpanchout** [comment]
![Screenshot 2021-07-27 at 16 48 52](https://user-images.githubusercontent.com/8115933/127176441-8b23f8f7-b2ba-4674-9594-576c7cc44370.png)

Leurs couleurs (bleu et rouge ADEME, pas Marianne) rendent pas si mal. On pourrait limite changer le thème "classique" de tous les simulateurs par ça

**Comment by martinregner** [comment]
C'est assez patriotique, mais ça rend bien ;)

**Comment by martinregner** [comment]
J'ai noté donc encore sur la charte :
- [ ] afficher les logos en haut
- [ ] modifier le fond de carte pour ne plus utiliser les nuances de vert ; proposition : des nuances de bleu à la place

**Comment by florianpanchout** [comment]
C'est bon pour les logos.

Il me reste encore la carte à modifier

**Comment by florianpanchout** [comment]
C'est bon pour la carte

**Comment by martinregner** [comment]
Top !
