### ISSUE TITLE
Mise à jour des données

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#16]
- [ ] Voir les possibilités de back office sur Koumoul

Si non satisfaisant (notamment pour Marilyne qui met à jour) :
- [ ] Valider la pérennité de l'ancien back office
- [ ] Mettre en place un export / import automatique
- [ ] Alternative : fichier Excel ou Airtable-like

**Comment by florianpanchout** [comment]
@martinregner Cette issue est traité ici non ? https://github.com/datagir/quefairedemesdechets/issues/22

**Comment by martinregner** [comment]
oui !
