### ISSUE TITLE
MEL QFDMD 01.10

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/quefairedemesdechets#17]
- [x] redirection à voir avec Julien Labe du service info
- [x] API des centres de collectes (cf. https://github.com/datagir/quefairedemesdechets/issues/15)
- [x] Iframe pour Agir
- [x] Synchronisation avec le service communication

**Comment by Clem-mrtn** [comment]
MAJ : mise en ligne semaine prochaine pour une communication officielle le 01/10

**Comment by florianpanchout** [comment]
Des news pour la mise en ligne ?
