### ISSUE TITLE
Optimisation graphique : réduire l'espace entre la barre de recherche & les suggestions &  

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/quefairedemesdechets#18]
Un espace trop grand entre la barre de recherche et les suggestions de recherche => créé un vide sur grand écran d'ordinateur + mobile

**Comment by florianpanchout** [comment]
Done

**Comment by Clem-mrtn** [comment]
OK pour moi 
Juste petite réflexion : est-ce que la rubrique _**" D'où viennent ces données"**_ n'est pas trop basse du coup sur grand écran ? 
![image](https://user-images.githubusercontent.com/76995768/132482748-fa5161be-9c73-4775-b250-a67bbeafc6cf.png)

Après pas forcément gênant puisqu'on a l'impression d'avoir le  Simulateur en entier d'un côté, et bon si on veut scroller on a toutes les infos de l'autre

**Comment by martinregner** [comment]
> Après pas forcément gênant puisqu'on a l'impression d'avoir le Simulateur en entier d'un côté, et bon si on veut scroller on a toutes les infos de l'autre

Oui je trouve ça assez cohérent comme ça

**Comment by florianpanchout** [comment]
Ce qui pose plus problème pour moi c'est l'absence de séparation entre les deux

**Comment by martinregner** [comment]
L'espace vertical c'est justement une bonne séparation non ? Tu veux dire qu'il faut le conserver ? (suis pour :)

**Comment by florianpanchout** [comment]
L'espace vertical n'existe que sur la home et sur grand écran. Sur une fiche produit, tu as tout à la suite et ne comprends pas trop visuellement ce qui est le contenu et ce qui est le footer

**Comment by martinregner** [comment]
l'espace ne se maintient pas toujours ? c'est selon le nombre de liens ?
![image](https://user-images.githubusercontent.com/46482115/132490270-85bb90d9-1d22-47e5-88d5-4c5deeeed4db.png)



J'aime bien l'idée d'une **vraie séparation**, avec un fond gris par ex., genre ci-dessous. Ce serait à appliquer à tous les simulateurs en revanche non ?...

![image](https://user-images.githubusercontent.com/46482115/132490632-6599f403-af4e-47ce-84e3-6b253dd4bcce.png)

**Comment by florianpanchout** [comment]
Yes, c'est ce que je souhaitais faire (le fond de couleur).

C'est déjà en place sur https://mesfruitsetlegumesdesaison.fr/

Normalement c'était sur tous mais ça s'est perdu au fil des itérations

**Comment by Clem-mrtn** [comment]
Oui carrément avec un fond de couleur je trouve que ça marque bien la démarcation et du coup ça fait peut-être un peu moins bizarre que d'avoir un grand vide blanc !
