### ISSUE TITLE
Rajouter les chiffres ? 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/quefairedemesdechets#2]
Réflexion : on rajouterai pas les chiffres ?
![image](https://user-images.githubusercontent.com/76995768/117121645-29ec0c80-ad95-11eb-8a9b-fff0bff0fcc4.png)

Histoire de contraster aussi avec le wording & ça peut rajouter un peu de couleur 
(un peu comme sur les autres simulateurs)

**Comment by florianpanchout** [comment]
Voir https://github.com/datagir/quefairedemesdechets/issues/1 pour éviter le mur de texte plutôt
