### ISSUE TITLE
Site Statique

### ISSUE THREAD

**Issue by florianpanchout** [datagir/quefairedemesdechets#20]
Pour l'instant, les pages sont générées à l'affichage du simulateur. Les pages déchets ne sont donc pas indexables.

On pourrait, en quelques jours, transformer le simulateur en un site statique. Ce serait quasi transparent pour l'utilisateur (le site serait plus rapide), et ça pourrait nous rapporter pas mal de trafic.

@martinregner @Clem-mrtn

**Comment by martinregner** [comment]
Super idée !

> en quelques jours

Ah oui quand-même ... grosse charge quand même. Un chantier possible "en parallèle" du reste du dev du site (ex. si jamais pas fini à la release, cela pourra quand même évoluer ensuite) ?

> Ce serait quasi transparent pour l'utilisateur (le site serait plus rapide), et ça pourrait nous rapporter pas mal de trafic.

Qu'est-ce que cela change ? en gros toutes les pages sont construites avant et quelque part (où...?), pas "en live" ?
Pas de changement pour l'iframe ?

**Comment by florianpanchout** [comment]
Ça demande de changer une bonne partie de l'architecture du site (et ça posera la question des mises à jour via Koumoul), mais ça peut être fait après la sortie oui.

Ce sera transparent pour les utilisateurs et réutilisateurs. Au lieu de télécharger un js qui construit la page à la volée sur la machine de l'utilisateur, la page est construite directement sur Netlify à chaque commit et l'utilisateur récupère le html

**Comment by florianpanchout** [comment]
Le site est maintenant statique ! Le contenu de chaque page peut être indexé par les moteurs de recherche (enfin quand il sera sur la vraie url)
