### ISSUE TITLE
Nouveau style

### ISSUE THREAD

**Issue by florianpanchout** [datagir/quefairedemesdechets#21]
J'ai modifié le thème pour essayer d'avoir quelque chose qui pourrait ensuite être repris par les autres simulateurs. Vous en pensez quoi ?

J'ai aussi simplifié le choix de thèmes en fonction. Il n'y a maintenant plus que clair et sombre comme options

**Comment by Clem-mrtn** [comment]
Jusque là pour le thème je vois pas un énoooorme changement 😅 t'as repris le rouge ADEME c'est ça ? 
Mais sinon ça va très bien !

Pour les thèmes je laisserais peut-être celui en noir & bleu _(thème simple_) : on a plusieurs réutilisateurs qui ont choisi de l'intégrer de cette façon, notamment sur MIT dont les couleurs ressemblent pas mal à QFDMD !

**Comment by martinregner** [comment]
un peu plus rouge le rouge oui ?
Pareil, je trouve ça très bien, notamment le bandeau gris du bas.

**Comment by florianpanchout** [comment]
Ahaha bien essayé mais le rouge n'a pas changé. C'était déjà le rouge Ademe :)

- J'ai changé la font des titres (et enlevé le surlignage du mot déchet)
- J'ai changé l'affichage du header (titre, logos, barre de recherche)
- J'ai ajouté un fond pour le footer

**Comment by martinregner** [comment]
en effet le clic sur "Déchet" n'était pas des plus indispensables ;)

**Comment by florianpanchout** [comment]
Coucou c'est encore moi, pour pleins de modifs que vous n'avez pas demandé !

Au programme : 
- J'ai remplacé la font par la Marianne. J'ai l'impression que ça va devenir un sujet, autant l'évacuer maintenant non ?
- J'ai enlevé les logos ADEME et Datagir en haut pour pouvoir afficher le titre à la place (ils sont toujours présents en bas)
- J'ai changé la couleur rouge pour qu'elle soit accessible sur le gris du footer (c'est subtil)
- J'ai changé la couleur du footer pour que le rouge soit accessible dessus (c'est subtil aussi)
- J'ai changé les couleurs du mode sombre (rouge plutôt que vert)
- J'ai fait plein de petits trucs chiants pour obtenir une note de 100/100 en accessibilité (via Google Lighthouse)

**Comment by Clem-mrtn** [comment]
Top pour tout ça !
Juste rajouter le logo ADEME du coup en haut

**Comment by florianpanchout** [comment]
Done

**Comment by Clem-mrtn** [comment]
Ok pour moi 👍

**Comment by martinregner** [comment]
Pareil !

**Comment by florianpanchout** [comment]
Devinez quoi ? J'ai encore changé le header. On a maintenant accès à la barre de recherche en permanence sur desktop.

C'est mieux non ?
