### ISSUE TITLE
Améliorer la map

### ISSUE THREAD

**Issue by florianpanchout** [datagir/quefairedemesdechets#24]
- [x] Adapter le zoom initial selon la distance des points d'apports
- [x] Ajouter un mode liste
- [x] Ajouter un indicateur de chargement
- [x] Ajouter un bouton itinéraire

**Comment by Clem-mrtn** [comment]
C'est un ticket à traiter avant la MEL ? (tu l'as mis dans Backlog)

**Comment by florianpanchout** [comment]
Il s'est mis tout seul dans backlog ; je vous laisse déterminer sa priorité :) 

(C'est mieux de le faire avant de mettre en prod. Mais on peut s'en passer)

**Comment by florianpanchout** [comment]
Done

**Comment by Clem-mrtn** [comment]
Mettre la barre de chargement en haut pour les petits écrans ?

**Comment by martinregner** [comment]
Des retours complémentaires de la part de Marilyne de la com :

- [ ] Peut-on ajouter un bouton + et – pour zoomer, dézoomer ?
- [ ] Peut-on légèrement réduire la taille de la carte (en hauteur seulement ?) ? Selon la taille de l'écran, on ne voit pas qu’il y a du texte en dessous.

**Comment by florianpanchout** [comment]
C'est fait !

(La carte s'adapte maintenant à la hauteur de l'écran)

**Comment by martinregner** [comment]
> (La carte s'adapte maintenant à la hauteur de l'écran)
Qu'il est fort 👍 

Top !
