### ISSUE TITLE
Connecter à Matomo

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#25]
- [x] suivi stat globale
- [x] suivi iframe
- [x] suivi du partage
- [x] suivi clics liens "En savoir plus"
- [x] suivi clics sur les fonctions de géoloc ?

**Comment by florianpanchout** [comment]
@laem J'ai besoin de toi pour la création de la propriété sur Matomo :)

**Comment by martinregner** [comment]
@florianpanchout tu peux suivre l'outil avant la mise en place de la redirection ?
Ou justement, comme c'est une redirection ça ne change rien ? 😋 (me faudra peut-être un petit dessin un jour pour bien comprendre 😄 )

**Comment by florianpanchout** [comment]
Le suivi ne dépend pas du nom de domaine mais du code du projet. Dans mon code je fais un appel à Matomo pour tracker la visite.

Matomo peut décider de ne tracker les visites que d'un nom de domaine (ce qu'on a mis en place sur nos simulateurs) pour être sur que ce ne soit pas quelqu'un qui s'amuse à faire des appels depuis ailleurs (et pour ne pas tracker les visites du dev).

Donc la on a aucun moyen de pouvoir tracker les visites du quefairedemesdechets actuel, puisque l'on a pas la main sur le code. Par contre ce serait bien d'avoir ces stats effectivement si l'on évalue notre impact par rapport au performance de l'existant. 

Je voulais aller acheter des crayons de couleur et il s'est mis à pleuvoir :( Promis tu auras un dessin un jour !

**Comment by florianpanchout** [comment]
Done !

**Comment by martinregner** [comment]
Merci ! (je ne sais pas pourquoi je ne le voyais pas dans ma liste...)
