### ISSUE TITLE
Quelques points de forme

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#28]
Des retours de Marilyne de la com :

- [x] Je pense qu’il ne faut pas indiquer sous le produit la catégorie car tous les produits ne l’ont pas (ils ont une « catégorie » quand ils sont des synonymes d’un type de produit pus général + on peut se retrouver avec des parenthèses dans des parenthèses). 
![image](https://user-images.githubusercontent.com/46482115/134634817-48135639-ac20-4327-8e94-0680ae708b87.png)

- [x] Il manque l’accent sur Où dans « Où l’apporter »

**Comment by florianpanchout** [comment]
Done
