### ISSUE TITLE
Champs de recherche : texte par défaut

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#29]
Retour de Marilyne de la com :
> plutôt que « entrez votre recherche, on pourrait mettre des exemples de produits, comme c’est déjà la cas. Qu’en penses-tu ?

On pourrait en effet avoir un CTA plus explicite / moins générique.

Quelques autres propositions :
1. Quel déchet cherchez vous ...
2. Entrez un déchet
3. Meuble, vêtement, ... entrez votre recherche

Qu'en pensez-vous @florianpanchout @Clem-mrtn ?

**Comment by florianpanchout** [comment]
J'ai mis "Entrez un déchet"
