### ISSUE TITLE
Reprendre mise en forme

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#3]
Si pas trop complexe pour cette première version, reprendre les puces + gras du texte source, ex. masque à usage unique : 
> ![image](https://user-images.githubusercontent.com/46482115/117136979-60338700-ada9-11eb-906e-41e8c32eae76.png)

**Comment by florianpanchout** [comment]
Je ne sais pas d'ou viens l'export intégré par Koumoul mais je doute que ça soit le fichier brut. Je n'ai aucun indicateur pour  les textes en gras et la syntaxe des puces n'est pas correcte.

Ce serait possible d'interpreter les puces (même si couteux en temps). Par contre je ne peux pas inventer les textes en gras.

Est ce qu'il est possible d'obtenir la version brute de la base ? Je pense qu'il sera plus simple de passer par la
