### ISSUE TITLE
Modifier la règle pour rechercher les déchets allant en déchéterie

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#31]
Le nouveau JDD sur Koumoul est désormais à jour : le code est "Sinoe" dans la colonne "Bdd".

La recherche sur le "déchèterie = true" est donc à remplacer par "Bdd = Sinoe"

**Comment by florianpanchout** [comment]
Done !

**Comment by martinregner** [comment]
Déjà ?! Top !
