### ISSUE TITLE
Lien vers Agir : ajout d'un paragraphe sous le simulateur

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#34]
Texte proposé par Marilyne :

> **Comment réduire ses déchets ?**
>
> Retrouvez tous les conseils de l’ADEME sur le site Agir pour la transition.

Lien vers : https://agirpourlatransition.ademe.fr/particuliers/maison/dechets

...voir même mettre le logo si ça passe : https://agirpourlatransition.ademe.fr/themes/custom/aw_theme_master/img/Logo-Agir-RVB.svg

**Comment by florianpanchout** [comment]
C'est fait !

(et le logo s'adapte au thème nuit)

**Comment by martinregner** [comment]
Top ! merci :)
