### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by florianpanchout** [datagir/quefairedemesdechets#37]
Il serait interessant de réfléchir à un titre et une meta description adaptés au SEO.

Je propose 

---
### Que Faire de mes Déchets ? Découvrez les solutions pour tous vos déchets et nos conseils pour en produire moins.

_Masque chirurgical ou ffp2, téléphone portable, médicaments, capsules de café, vêtements... Découvrez ici comment les recycler, les trier, les éviter ou les jeter !_

---

Ce serait aussi bien d'avoir un texte plus fourni dans le footer (là ou on parle d'Agir) avec plus de mots clés. Je n'ai pas les compétences pour l'écrire par contre.

(À noter que vu que l'url a été une redirection vers Agir pendant très longtemps, on va galérer à le lancer. Peut être serait il judicieux de créer le sous domaine quefairedemesdechets.ademe.fr et de rediriger quefairedemesdechets.fr dessus).

**Comment by Clem-mrtn** [comment]
=> à voir avec Chaïb ?

**Comment by florianpanchout** [comment]
Nope, on garde cette url et on attend
