### ISSUE TITLE
Modifier suggestions par défaut

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#4]
Enlever "Révolver" et ajouter "masque à usage unique"

**Comment by florianpanchout** [comment]
Je ne vois pas en quoi les gens jetteraient plus de masque que de revolver 

(c'est fait)

**Comment by martinregner** [comment]
je le vois pas encore en prod mais je patiente :)

**Comment by florianpanchout** [comment]
My bad. Erreur au déploiement. C'est corrigé :)

**Comment by florianpanchout** [comment]
@martinregner Est ce qu'on met à jour ces suggestions maintenant que l'on sait quel sont les déchets les plus recherchés ?

**Comment by martinregner** [comment]
Oui. Je propose, pour inspirer tout en répondant au plus recherché :
•	Câble
•	Téléphone mobile
•	Médicaments
•	Capsules de café
•	Chaussures
•	Vêtement

**Comment by florianpanchout** [comment]
Peut être laisser "Masque à usage unique" non ?

**Comment by florianpanchout** [comment]
Done !
