### ISSUE TITLE
API fusée de détresse

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#42]
Pour les [fusees-de-detresse](https://quefairedemesdechets.fr/dechet/fusees-de-detresse) une API existe : https://extranet.aper-pyro.fr/api_documentation/

Faut-il modifier la base de données pour ne plus appeler les déchèteries mais appeler cette API ici ?

**Comment by martinregner** [comment]
Plus d'info sur cette filière : https://www.aper-pyro.fr/qui-sommes-nous/

**Comment by florianpanchout** [comment]
Je doute (treeeeees fortement) que le temps nécessaire à l'intégration d'une nouvelle api (1/2 journée) soit correctement investi dans cette tache. 

Peut être plutôt enlever la carte des déchèteries et mettre un lien vers https://www.aper-pyro.fr/les-points-de-collecte/ dans la description du déchet ?

**Comment by martinregner** [comment]
Oui très bien.
Le problème est que ce lien devrait déjà s'afficher... J'ai demandé à Nicolas pour mieux comprendre le back office. Pas très clair

**Comment by martinregner** [comment]
C'est ajouté : https://quefairedemesdechets.fr/dechet/fusees-de-detresse/

(J'ai regardé, c'est bien un produit pyro pour certains détaupeurs 😨 ... les pauvres bêtes !)
