### ISSUE TITLE
Relier les retours utilisateurs à un formulaire Airtable 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/quefairedemesdechets#45]
Suite aux retours utilisateurs on s'est rendu compte que l'explort .csv est vmt pas top pour les traiter
Une grande partie des retours ne nous concernent pas donc si on fait une redirection sur notre mail on passerait pas mal de temps à les transférer... 

Du coup solution ! 
=> créer un airtable où Marilyne aurait aussi ses accès pour aller consulter les retours qui la concerne (environ 90%) 

A discuter 😄

**Comment by florianpanchout** [comment]
J'ai créé deux Zappier qui viennent remplir ce tableau : https://airtable.com/apptStfEVXNDeuoPy/tblinvoOjVLB8yusN/viwui171Q6KidjI1Z?blocks=hide

**Comment by martinregner** [comment]
...le tout dans le respect de la charte graphique ! 😃 
Si on rajoute des colonnes (tag, case à cocher) ça ne perturbera pas a priori ?

**Comment by florianpanchout** [comment]
"Normalement" non. Il faut juste laisser les colonnes existantes
