### ISSUE TITLE
L'iframe se charge en mode mobile sur longuevieauxobjets

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#46]
cf. https://longuevieauxobjets.gouv.fr/trier-recycler

Au delà de l'affichage, cela empêche par exemple de chercher un nouveau déchet.

Voici leur retour ci-dessous ; qu'en penses-tu ?

> L’iframe étant responsive, compte tenu de la charte graphique du site longuevie et notamment de la largeur de la colonne centrale dans laquelle il est intégré (moins importante que celle du site agir), il bascule automatiquement en mode mobile/tablette. Pour y remédier, vous pourriez modifier les règles d'affichage qui régissent la bascule entre vue mobile et vue desktop mais cela risquerait d’avoir un impact sur d’autres sites où est affiché l’iframe.

**Comment by florianpanchout** [comment]
J'ai modifié la largeur max pour la version mobile et redimensionné le header en fonction. La barre de recherche s'affiche maintenant
