### ISSUE TITLE
La section "Comment l'éviter ?" ne se charge pas

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#47]

**Comment by florianpanchout** [comment]
L'attribut a été renommé côté Koumoul (de `Comment_les_Ã©viter_?` à `Comment_les_eviter_?`). 

J'ai répercuté la modification de notre côté. Ça fonctionne à nouveau

**Comment by martinregner** [comment]
Super, merci @florianpanchout !
J'en reparle à Koumoul...
