### ISSUE TITLE
Redirection du site

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#51]
Pour la campagne du Ministère, l'URL  quefairedemesdechets.fr doit rediriger vers le site de campagne (quefairedemesdechets.gouv.fr) à compter du 17 octobre (si pas de décalage).

Conséquence pour nous : il faut "déplacer" l'outil sur quefairedemesdechets.ademe.fr

Après échange avec @jondu33 le plus opportun est de réaliser le transfert de l'outil sur quefairedemesdechets.ademe.fr et rediriger quefairedemesdechets.fr vers ce "nouveau" site dans un premier temps, en attendant que le site de campagne soit opérationnel.

Pour les iframes : il y en a peu ; nous pouvons essayer de tous les contacter pour leur signaler le changement

**Comment by florianpanchout** [comment]
Demande faite auprès du "Pole infrastructure" de l'ADEME

**Comment by florianpanchout** [comment]
quefairedemesdechets.fr redirige maintenant vers quefairedemesdechets.ademe.fr
