### ISSUE TITLE
Nouveau point d'apport - Panneaux photovoltaïques

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#52]
Comme discuté @florianpanchout des nouvelles filières vont arriver via [ce portail dédié](https://koumoul.com/data-fair-portals/?portalId=c31a39c0-65d7-4af3-bb64-30f23248b8be).

Le premier jeu de données (et le seul pour le moment) concerne [le photovoltaïque](https://koumoul.com/data-fair-portals/datasets?portalId=c31a39c0-65d7-4af3-bb64-30f23248b8be).

Pourrais-tu ajouter ces points de géolocalisation ?
Au passage, si quelque chose cloche dans le format, il est encore temps de le dire avant que toutes les filières arrivent sous ce format.

**Comment by florianpanchout** [comment]
[C'est visible ici](https://deploy-preview-53--quefairedemesdechets.netlify.app/dechet/panneaux-photovoltaiques)

Il y en a très peu pour l'instant (12). Tu peux essayer de chercher `230 avenue d'uchamp` comme adresse pour voir à quoi ça ressemble.

[J'ai créé une issue](https://github.com/datagir/quefairedemesdechets/issues/54) pour gérer la carte vide lorsqu'il n'y a pas de point d'apport à proximité

Il y a plein d'info supplémentaire [disponible via l'api](https://koumoul.com/data-fair/api/v1/datasets/points-dapport-soren-pv/lines). Qu'est ce qui vaut le coup d'être affiché sur le marqueur ?
