### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#6]
**Où** l'apporter ?
Que **va-t-il** devenir ?

**Comment by florianpanchout** [comment]
Done

**Comment by martinregner** [comment]
Possible de garder la case du milieu sur une seule ligne ?
![image](https://user-images.githubusercontent.com/46482115/125095499-87257680-e0d4-11eb-9ae9-a85cbcff7cf9.png)

**Comment by florianpanchout** [comment]
Ah oui. C'est corrigé
