### ISSUE TITLE
Géoloc pharmacie pour les médicaments

### ISSUE THREAD

**Issue by martinregner** [datagir/quefairedemesdechets#7]
Dans la version actuelle, basée sur google.
Possible de refaire pareil ?

**Comment by martinregner** [comment]
> Pour l'instant je reprends l'api Mapbox (qui a comme défaut de limiter à 10 le nombre de résultats)

Ressort directement les pharmacies ?
10 c'est déjà pas mal...!

> Et les jeux de données de data.gouv ne sont pas interrogeables...

A télécharger puis mettre à jour à la sortie d'une nouvelle version ?

⚠️ J'ai l'impression que les déchèteries s'affichent en + des pharmacies. C'est génant pour les médicaments, par contre pour d'autres déchets ça pourra être pertinent.

**Comment by florianpanchout** [comment]
> Ressort directement les pharmacies ?

Yes

> A télécharger puis mettre à jour à la sortie d'une nouvelle version ?

Y'a 32Mo de csv. Donc impossible à gérer sans api

> ⚠️ J'ai l'impression que les déchèteries s'affichent en + des pharmacies. C'est génant pour les médicaments, par contre pour d'autres déchets ça pourra être pertinent.

Parce qu'il y a écrit "un point de collecte qui l'accepte (pharmacie d'officine ou hospitalière, déchèterie..." à chaque fois
